forum/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('event/', views.event, name='event'),
    path('event/event-detail/<int:event_id>/',views.event_detail, name='detail-event'),
    path('mypost/edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('myprojects/', views.myprojects, name='myprojects'),
    path('myprojects/proyek-pribadi/',views.proyek_pribadi, name='proyek-pribadi'),
    path('myprojects/proyek-pribadi/pelamar/<int:proyek_id>/',views.proyek_pribadi_detail, name='proyek-pribadi-detail'),
    path('myprojects/proyek-dilamar/', views.proyek_dilamar, name='proyek-dilamar'),
    path('myprojects/proyek-dilamar/delete/<int:pk>/', views.delete_lamar_proyek, name='delete_lamar_proyek'),
    path('mypost/', views.mypost, name='mypost'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('materi-kuliah/', views.materiKuliah, name='materiKuliah'),
    path('get-mata-kuliah/', views.get_mata_kuliah, name='get_mata_kuliah'),
    path('buat-posting/', views.buat_post, name='buatPost'),
    path('materi-kuliah/detail-posting/<int:post_id>/',views.detail_post, name='detailPost'),
    path('add_comment/<int:post_id>/', views.add_comment, name='add_comment'),
    path('delete_comment/', views.delete_comment, name='delete_comment'),
    path('delete-post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('download-file/<path:filename>/',views.download_file, name='download_file'),
    path('proyek-kolaboratif/', views.proyek_kolaboratif,name='proyek-kolaboratif'),
    path('buat-proyek/', views.buat_proyek, name='buat_proyek'),
    path('proyek-detail/<int:proyek_id>/',views.proyek_detail, name='proyek-detail'),
    path('proyek-kolaboratif/bergabung-sekarang/<int:proyek_id>/',views.submit_application, name='submit_application'),
    path('filter_projects/', views.filter_projects, name='filter_projects'),
    path('terima-pelamar/<int:pelamar_id>/', views.terima_pelamar, name='terima_pelamar'),
    path('tolak-pelamar/<int:pelamar_id>/', views.tolak_pelamar, name='tolak_pelamar'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.exceptions import ValidationError


class KatMateri(models.Model):
    id = models.AutoField(primary_key=True)
    nama = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nama

    class Meta:
        verbose_name_plural = "Kategori Materi"
        ordering = ['id']


class MataKuliah(models.Model):
    id = models.AutoField(primary_key=True)
    nama = models.CharField(max_length=50)
    semester = models.ForeignKey(KatMateri, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nama

    class Meta:
        verbose_name_plural = "Mata Kuliah"
        ordering = ['id']


class Post(models.Model):
    id = models.AutoField(primary_key=True)
    # Replace 'uploads/' with desired path
    file_upload = models.FileField(blank=True, null=True, upload_to='uploads/')
    judul = models.CharField(max_length=100)
    deskripsi = models.CharField(max_length=100)
    semester = models.ForeignKey(KatMateri, on_delete=models.CASCADE)
    matkul = models.ForeignKey(MataKuliah, on_delete=models.CASCADE)
    pengguna = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.judul

    class Meta:
        verbose_name_plural = "Posting"
        ordering = ['id']


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.post.judul}'

    class Meta:
        verbose_name_plural = "Comment"


class Proyek(models.Model):
    KATEGORI_CHOICES = [
        ('lomba', 'Lomba'),
        ('pengabdian', 'Pengabdian'),
        ('individu', 'Individu'),
    ]

    STATUS_CHOICES = [
        ('diterima', 'Diterima'),
        ('direview', 'Direview'),
        ('ditolak', 'Ditolak'),
    ]

    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    sampul = models.ImageField(upload_to='sampul_proyek/')
    judul = models.CharField(max_length=255)
    deskripsi = models.TextField()
    syarat = models.TextField()
    kategori_proyek = models.CharField(max_length=10, choices=KATEGORI_CHOICES)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.judul

    class Meta:
        verbose_name_plural = "Proyek"


class Event(models.Model):
    id = models.AutoField(primary_key=True)
    pamflet = models.ImageField(upload_to='event_covers/')
    judul = models.CharField(max_length=200)
    deskripsi = models.TextField()
    tanggal = models.DateTimeField()
    url = models.URLField(max_length=200, default='https://google.com')

    def __str__(self):
        return self.judul

    class Meta:
        verbose_name_plural = "Event"


def validate_file_extension(value):
    if not value.name.endswith('.pdf'):
        raise ValidationError("Hanya file PDF saja yang diperbolehkan.")


class LamarProyek(models.Model):
    STATUS_CHOICES = [
        ('menunggu', 'Menunggu'),
        ('direview', 'Direview'),
        ('diterima', 'Diterima'),
    ]

    KATEGORI_CHOICES = [
        ('lomba', 'Lomba'),
        ('pengabdian', 'Pengabdian'),
        ('individu', 'Individu'),
    ]
    nama = models.CharField(max_length=100)
    jurusan = models.CharField(max_length=100)
    cv = models.FileField(upload_to='cv/', validators=[validate_file_extension])
    kategori = models.CharField(max_length=10, choices=KATEGORI_CHOICES, null=True, blank=True)
    nama_proyek = models.ForeignKey(Proyek, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='menunggu')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.nama

    class Meta:
        verbose_name_plural = "LamarProyek"

forum/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import KatMateri, MataKuliah, Post, Comment, Proyek, Event, LamarProyek
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.http import JsonResponse
from django.contrib.auth import logout as django_logout
from django.http import HttpResponse, Http404
import os
from django.contrib import messages
from django.utils import timezone
from django.views.decorators.http import require_POST
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def home(request):
    return render(request, 'index.html')


def myprojects(request):
    return render(request, 'myprojects.html')


@login_required
def proyek_pribadi(request):
    user_projects = Proyek.objects.filter(user=request.user)
    paginator = Paginator(user_projects, 4)  # Show 4 projects per page

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'proyek-pribadi.html', {'page_obj': page_obj})

@login_required
def proyek_pribadi_detail(request, proyek_id):
    proyek = get_object_or_404(Proyek, id=proyek_id)
    pelamar = LamarProyek.objects.filter(nama_proyek=proyek)

    return render(request, 'proyek-pribadi-detail.html', {
        'proyek': proyek,
        'pelamar': pelamar
    })

@login_required
def proyek_dilamar(request):
    user = request.user
    proyek_dilamar_list = LamarProyek.objects.filter(user=user)
    paginator = Paginator(proyek_dilamar_list, 4)  # Batasi 4 card per halaman

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'proyek-dilamar.html', {'page_obj': page_obj})

def proyek_detail(request, proyek_id):
    proyek = get_object_or_404(Proyek, pk=proyek_id)
    context = {
        'proyek': proyek
    }
    return render(request, 'proyek-detail.html', context)


def event_detail(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    return render(request, 'event-detail.html', {'event': event})


def event(request):
    events = Event.objects.all()
    return render(request, 'event.html', {'events': events})


def proyek_kolaboratif(request):
    proyek_diterima = Proyek.objects.filter(status='diterima')
    context = {
        'proyek_diterima': proyek_diterima
    }
    return render(request, 'proyek-kolaboratif.html', context)


def contact(request):
    return render(request, 'contact.html')


@login_required(login_url='/login/')
def mypost(request):
    posts = Post.objects.filter(pengguna=request.user)
    context = {
        'posts': posts,
    }
    return render(request, 'mypost.html', context)


def detail_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post,
    }
    return render(request, 'post-details.html', context)


def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    # Get and remove the flag from session
    edit_success = request.session.pop('edit_success', False)

    if request.method == 'POST':
        try:
            # Check if a new image is uploaded
            if 'gambar' in request.FILES:
                post.gambar = request.FILES['gambar']

            # Update judul and deskripsi
            post.judul = request.POST.get('judul', post.judul)
            post.deskripsi = request.POST.get('deskripsi', post.deskripsi)

            post.save()

            # Set a flag or variable to indicate success
            request.session['edit_success'] = True
            return redirect('edit_post', post_id=post.id)
        except Exception as e:
            # Optionally, handle specific exceptions here if needed
            print(f'Gagal mengubah data. Kesalahan: {e}')
            messages.error(request, f'Gagal mengubah data. Kesalahan: {e}')
            return redirect('edit_post', post_id=post.id)

    return render(request, 'edit.html', {'post': post, 'edit_success': edit_success})


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('home')
        else:
            return render(request, 'login.html', {'error': 'Invalid username or password'})
    else:
        return render(request, 'login.html')


def logout_user(request):
    django_logout(request)
    return redirect('login')


def materiKuliah(request):
    posts_list = Post.objects.all()
    paginator = Paginator(posts_list, 5)  # Show 5 posts per page

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    kategori_materi = KatMateri.objects.all()
    mata_kuliah = MataKuliah.objects.all()
    context = {
        'posts': posts,
        'kategori_materi': kategori_materi,
        'mata_kuliah': mata_kuliah,
    }
    return render(request, 'materiKuliah.html', context)


def get_mata_kuliah(request):
    semester_id = request.GET.get('semester_id')
    mk_id = request.GET.get('mk_id')

    if semester_id:
        # Jika hanya semester_id yang ada, kembalikan daftar mata kuliah
        mata_kuliah = MataKuliah.objects.filter(
            semester_id=semester_id).values('id', 'nama')
        return JsonResponse(list(mata_kuliah), safe=False)
    elif mk_id:
        # Jika hanya mk_id yang ada, kembalikan postingan berdasarkan mata kuliah yang dipilih
        posts = Post.objects.filter(matkul_id=mk_id)
        return render(request, 'partials/post_list.html', {'posts': posts})
    else:
        # Jika tidak ada parameter yang diberikan, kembalikan semua postingan
        posts = Post.objects.all()
        return render(request, 'partials/post_list.html', {'posts': posts})


def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        password = request.POST['password']
        repeat_password = request.POST['repeat_password']
        if password == repeat_password:
            user = User.objects.create_user(
                username=username, password=password, first_name=first_name, last_name=last_name)
            user.save()
            return redirect('login')
        else:
            return render(request, 'register.html', {'error': 'Passwords do not match'})
    else:
        return render(request, 'register.html')


@login_required(login_url='/login/')
def buat_post(request):
    if request.method == 'POST':
        judul = request.POST['judul']
        deskripsi = request.POST['deskripsi']
        semester_id = request.POST.get('semester')
        matkul_id = request.POST.get('matakuliah')
        file_upload = request.FILES.get(
            'file_upload')  # Access the uploaded file

        if judul and deskripsi and semester_id and matkul_id:
            try:
                semester = KatMateri.objects.get(id=semester_id)
                matkul = MataKuliah.objects.get(id=matkul_id)
                post = Post(judul=judul, deskripsi=deskripsi,
                            semester=semester, matkul=matkul, pengguna=request.user)

                if file_upload:
                    post.file_upload = file_upload  # Save the uploaded file

                post.save()
                request.session['create_success'] = True  # Set success flag
                # Redirect to the same view to display the success message
                return redirect('materiKuliah')
            except (KatMateri.DoesNotExist, MataKuliah.DoesNotExist):
                return render(request, 'error.html', {'error_message': 'Data tidak valid'})
        else:
            return render(request, 'error.html', {'error_message': 'Formulir tidak lengkap'})
    else:
        # Retrieve and remove the flag from the session
        create_success = request.session.pop('create_success', False)
        return render(request, 'buatPosting.html', {
            'kategori_materi': KatMateri.objects.all(),
            'create_success': create_success
        })


def add_comment(request, post_id):
    if request.method == 'POST':
        comment_content = request.POST.get('comment')
        if comment_content:
            post = get_object_or_404(Post, pk=post_id)
            comment = Comment.objects.create(
                post=post, user=request.user, content=comment_content, created_at=timezone.now())
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                response = {
                    'success': True,
                    'user': {
                        'username': comment.user.username,
                    },
                    'content': comment.content,
                    'created_at': comment.created_at.strftime('%d %B %Y %H:%M')
                }
                return JsonResponse(response)
    return redirect('detail_post', post_id=post_id)


@require_POST
def delete_comment(request):
    comment_id = request.POST.get('comment_id')
    comment = get_object_or_404(Comment, id=comment_id, user=request.user)
    post_id = comment.post.id
    comment.delete()
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return JsonResponse({'success': True})
    return redirect('detail_post', post_id=post_id)

@login_required
def delete_lamar_proyek(request, pk):

forum/templates/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Edit Postingan | Forum</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600&family=Playfair+Display:wght@400;500;600&display=swap" rel="stylesheet" />

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

    {% load static %}
    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet" />
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  </head>

  <body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
      <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>
    <!-- Spinner End -->

    <!-- Navbar & Hero Start -->
    {% include 'partials/navbar.html' %}
    <!-- Navbar End -->

    <!-- Header Start -->
    <div class="container-fluid bg-breadcrumb">
      <div class="container text-center py-5" style="max-width: 900px;">
        <h3 class="text-white display-3 mb-4 wow fadeInDown" data-wow-delay="0.1s">Edit Postingan Anda</h3>
      </div>
    </div>
    <!-- Header End -->

    <!-- Edit Start -->
    <div class="container-fluid appointment py-5 d-flex justify-content-center align-items-center" style="min-height: 100vh;">
      <div class="container py-5">
        <div class="row g-5 align-items-center justify-content-center">
          <div class="col-lg-6 wow fadeInRight" data-wow-delay="0.4s">
            <div class="appointment-form rounded p-5">
              <h1 class="display-5 mb-4">Edit Postingan</h1>
              {% if messages %}
                <div>
                  {% for message in messages %}
                    <div class="alert {% if message.tags %}
                        alert-{{ message.tags }}
                      {% endif %}">{{ message }}</div>
                  {% endfor %}
                </div>
              {% endif %}

              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row gy-3 gx-4">
                  <div class="col-xl-12">
                    <input type="file" name="gambar" class="form-control py-3 border-primary bg-transparent" placeholder="Gambar" />
                  </div>
                  <div class="col-xl-12">
                    <input type="text" name="judul" class="form-control py-3 border-primary bg-transparent" placeholder="Judul" value="{{ post.judul }}" />
                  </div>
                  <div class="col-xl-12">
                    <textarea name="deskripsi" class="form-control py-3 border-primary bg-transparent" placeholder="Deskripsi">{{ post.deskripsi }}</textarea>
                  </div>
                  <div class="col-12">
                    <button type="submit" class="btn btn-primary text-white w-100 py-3 px-5">SUBMIT NOW</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Edit End -->

    <!-- Modal Video -->
    <div class="modal fade" id="videoModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content rounded-0">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Youtube Video</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <!-- 16:9 aspect ratio -->
            <div class="ratio ratio-16x9">
              <iframe class="embed-responsive-item" src="" id="video" allowfullscreen allowscriptaccess="always" allow="autoplay"></iframe>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% include 'partials/footer.html' %}

    <!-- Back to Top -->
    <a href="#" class="btn btn-primary btn-lg-square back-to-top"><i class="fa fa-arrow-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>

    <script>
        // Check for edit success flag in session
        {% if edit_success %}
          // Display alert and redirect on OK
          alert('Data berhasil diubah');
          window.location.href = "{% url 'mypost' %}";
        {% endif %}
      </script>
  </body>
</html>

forum/templates/proyek-dilamar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Forum | Proyek Yang Dilamar</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600&family=Roboto&display=swap" rel="stylesheet" />

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

    {% load static %}
    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet" />
    <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  </head>
  <style>
    .pdf-icon {
        color: red;
      }
    .causes-item {
      border: 1px solid #ddd;
      border-radius: 8px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      overflow: hidden;
      transition: transform 0.3s, box-shadow 0.3s;
    }
    
    .causes-item:hover {
      transform: translateY(-5px);
      box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    }
    
    .causes-img {
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: #f8f9fa;
      padding: 20px;
    }
    
    .causes-content {
      padding: 20px;
    }
    
    .causes-content h4 {
      font-weight: bold;
      color: #333;
    }
    
    .causes-content p {
      color: #777;
    }
    
    .causes-content .badge {
      font-size: 14px;
    }
    
    .causes-content .btn {
      transition: background-color 0.3s, color 0.3s;
    }
    
    .causes-content .btn:hover {
      background-color: #0056b3;
      color: #fff;
    }
  </style>
  <body>
    <!-- Spinner Start -->
    <div id="spinner" class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50 d-flex align-items-center justify-content-center">
      <div class="spinner-grow text-primary" role="status"></div>
    </div>
    <!-- Spinner End -->

    <!-- Navbar start -->
    {% include 'partials/navbar.html' %}
    <!-- Navbar End -->

    <!-- Header Start -->
    <div class="container-fluid bg-breadcrumb">
      <div class="container text-center py-5" style="max-width: 900px;">
        <h3 class="text-white display-3 mb-4">Proyek Yang Dilamar</h3>
      </div>
    </div>
    <!-- Header End -->

    <!-- Causes Start -->
    <div class="container-fluid causes py-5">
      <div class="container py-5">
          <div class="text-center mx-auto pb-5" style="max-width: 800px;">
              <h5 class="text-uppercase text-primary">Proyek Yang Dilamar</h5>
          </div>
          <div class="row g-4">
              {% for proyek in page_obj %}
                  <div class="col-lg-6 col-xl-3">
                      <div class="causes-item">
                          <div class="causes-img">
                              <!-- CV Icon -->
                              <i class="fas fa-file-pdf fa-3x"></i>
                          </div>
                          <div class="causes-content p-4">
                              <span class="mb-3 badge text-bg-info">{{ proyek.get_kategori_display }}</span>
                              <h4 class="mb-3">{{ proyek.nama_proyek }}</h4>
                              <p class="mb-4">Status: {{ proyek.get_status_display }}</p>
                              <a class="btn-hover-bg btn btn-danger text-white py-2 px-3" href="{% url 'delete_lamar_proyek' proyek.pk %}">Hapus</a>
                          </div>
                      </div>
                  </div>
              {% endfor %}
          </div>
          <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-center mt-3">
                  {% if page_obj.has_previous %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                      </li>
                  {% endif %}
                  {% for num in page_obj.paginator.page_range %}
                      <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                      </li>
                  {% endfor %}
                  {% if page_obj.has_next %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
                      </li>
                  {% endif %}
              </ul>
          </nav>
      </div>
  </div>
  
    <!-- Causes End -->

    <!-- Footer Start -->
    {% include 'partials/footer.html' %}
    <!-- Footer End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-primary btn-primary-outline-0 btn-md-square back-to-top"><i class="fa fa-arrow-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>